language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "python setup.py develop"
# command to run tests
script: "python tests.py"
notifications:
  slack: kellycreativetech:X6Zy35F8Ty380Q1mhG68jzu6